version: '3.8'

services:
  postgres:
    image: postgres:17.3-alpine
    container_name: quorum_challenge_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=quorum_db
      - POSTGRES_USER=quorum_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-$(openssl rand -hex 16)}
    networks:
      - quorum_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

volumes:
  postgres_data:
    driver: local

networks:
  quorum_network:
    driver: bridge
